name: Deploy PengEngine

on:
  push:
    tags:
      - '**'    
jobs:
  build:
    strategy:
      matrix:
        configuration: [Master, Release, Development, Debug]
        os: [windows-latest]

    env:
      binary_path: D:\a\PengEngine\PengEngine\\out\x64\${{ matrix.configuration }}\
      archive_name: '${{ github.event.repository.name }}-${{ matrix.configuration }}-${{ github.ref_name }}'
    name: Build on windows
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
        
    - name: Build app for release
      run: msbuild /p:configuration=${{ matrix.configuration }} /t:rebuild PengEngine.sln

    - name: Zip the project
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ env.archive_name }}.zip"
        path: "${{ env.binary_path }}"

    - name: Cache artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.archive_name }}"
        path: "*.zip"
        overwrite: true
        retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*/*.zip"
        token: ${{ secrets.API_TOKEN }}
        allowUpdates: true