name: Compile PengEngine

on:
  workflow_dispatch:

jobs:
  windows:
    name: build on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[16.4,16.5)'
        msbuild-architecture: x64
        

    - name: Build app for release
      run: msbuild PengEngine.vcxproj /p:configuration=master /p:PreferredToolArchitecture=x64